frameworkVersion: '3'
org: kylepls
service: kylepls2-site-diff

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 'ses:SendEmail'
      Resource: "arn:aws:ses:us-east-1:088327297714:identity/mail@kyle.in"

functions:
  rateHandler:
    handler: index.run
    memorySize: 1024
    timeout: 15
    layers:
      # Google Chrome for AWS Lambda as a layer
      # Make sure you use the latest version depending on the region
      # https://github.com/shelfio/chrome-aws-lambda-layer
      - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:10

    events:
      - schedule: rate(15 minutes)
